"""
Dead code moved out of ``src/seiche/maps.py``.

The ``labels`` entries of ``MAPS`` were never read by the pipeline nor the
unit tests. Kept here as reference, can be re-integrated if needed.
"""

MAPS_LABELS = {
    "oso23": {
        1: "Urbain dense",
        2: "Urbain diffus",
        3: "Zone industrielle et commerciale",
        4: "Routes",
        5: "Oléagineux d'hiver",
        6: "Céréales à paille",
        7: "Protéagineux de printemps",
        8: "Soja",
        9: "Tournesol",
        10: "Mais",
        11: "Riz",
        12: "Tubercules/racines",
        13: "Prairies",
        14: "Vergers",
        15: "Vignes",
        16: "Forêts de feuillus",
        17: "Fôrets de conifères",
        18: "Pelouses",
        19: "Landes",
        20: "Surfaces minérales",
        21: "Plages et dunes",
        22: "Glaciers et neiges éternelles",
        23: "Eau",
    },
    "esawc": {
        10: "Tree Cover",
        20: "Shrubland",
        30: "Grassland",
        40: "Cropland",
        50: "Built-up",
        60: "Bare / sparse vegetation",
        70: "Snow and ice",
        80: "Permanenet water bodies",
        90: "Herbaceous wetland",
        95: "Mangroves",
        100: "Moss and lichen",
    },
    "rpg": {
        1: "Blé tendre",
        2: "Maïs grain et ensilage",
        3: "Orge",
        4: "Autres céréales",
        5: "Colza",
        6: "Tournesol",
        7: "Autres oléagineux",
        8: "Protéagineux",
        9: "Plates à fibre",
        10: "???",
        11: "Gel",
        12: "???",
        13: "???",
        14: "Riz",
        15: "Légumineuses à grain",
        16: "Fourrage",
        17: "Estives et landes",
        18: "Prairies permanentes",
        19: "Prairies temporaires",
        20: "Vergers",
        21: "Vignes",
        22: "Fruits à coques",
        23: "Oliviers",
        24: "Autres cultures industrielles",
        25: "Légumes ou fleurs",
        26: "Canne à sucre",
        27: "???",
        28: "Divers",
    },
}
